M48
; DRILL file {KiCad 9.0.7} date 2026-07-30T10:55:19-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-30T10:55:19-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X77.844Y-33.5
T2
X48.0Y-27.0
X48.0Y-29.0
X48.0Y-31.0
X79.4Y-26.5
X79.4Y-28.5
X79.4Y-30.5
X79.4Y-32.5
M30
